class Language:

    ENGLISH = 'en'

    choices = (
        ('af', 'Afrikaans'),
        ('ar', 'Arabic'),
        ('az', 'Azerbaijani'),
        ('bg', 'Bulgarian'),
        ('be', 'Belarusian'),
        ('bn', 'Bengali'),
        ('br', 'Breton'),
        ('bs', 'Bosnian'),
        ('ca', 'Catalan'),
        ('cs', 'Czech'),
        ('cy', 'Welsh'),
        ('da', 'Danish'),
        ('de', 'German'),
        ('el', 'Greek'),
        ('en', 'English'),
        ('eo', 'Esperanto'),
        ('es', 'Spanish'),
        ('et', 'Estonian'),
        ('eu', 'Basque'),
        ('fa', 'Persian'),
        ('fi', 'Finnish'),
        ('fr', 'French'),
        ('fy-nl', 'Frisian'),
        ('ga', 'Irish'),
        ('gl', 'Galician'),
        ('he', 'Hebrew'),
        ('hi', 'Hindi'),
        ('hr', 'Croatian'),
        ('hu', 'Hungarian'),
        ('ia', 'Interlingua'),
        ('id', 'Indonesian'),
        ('is', 'Icelandic'),
        ('it', 'Italian'),
        ('ja', 'Japanese'),
        ('ka', 'Georgian'),
        ('kk', 'Kazakh'),
        ('km', 'Khmer'),
        ('kn', 'Kannada'),
        ('ko', 'Korean'),
        ('lb', 'Luxembourgish'),
        ('lt', 'Lithuanian'),
        ('lv', 'Latvian'),
        ('mk', 'Macedonian'),
        ('ml', 'Malayalam'),
        ('mn', 'Mongolian'),
        ('my', 'Burmese'),
        ('nb', 'Norwegian Bokmal'),
        ('ne', 'Nepali'),
        ('nl', 'Dutch'),
        ('nn', 'Norwegian Nynorsk'),
        ('os', 'Ossetic'),
        ('pa', 'Punjabi'),
        ('pl', 'Polish'),
        ('pt', 'Portuguese'),
        ('ro', 'Romanian'),
        ('ru', 'Russian'),
        ('sk', 'Slovak'),
        ('sl', 'Slovenian'),
        ('sq', 'Albanian'),
        ('sr', 'Serbian'),
        ('sv', 'Swedish'),
        ('sw', 'Swahili'),
        ('ta', 'Tamil'),
        ('te', 'Telugu'),
        ('th', 'Thai'),
        ('tr', 'Turkish'),
        ('tt', 'Tatar'),
        ('udm', 'Udmurt'),
        ('uk', 'Ukrainian'),
        ('ur', 'Urdu'),
        ('vi', 'Vietnamese'),
        ('zh-cn', 'Simplified Chinese'),
        ('zh-tw', 'Traditional Chinese'),
    )

    choices_dict = dict([(k, v) for k, v in choices])
